### ISSUE TITLE
0.2.1 release check list

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/oauth2#101]
## Reason
Minor release (Bugfix) needed #100 

## QA
- [x] Create release branch -> https://github.com/owncloud/oauth2/tree/release/0.2.1
- [x] ~~Create "$version Testplan"~~ N/A
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) -> https://github.com/owncloud/QA/pull/498/files#diff-773b0c5814dfa52f9ff39e5a55c955c8

**Docs**
- [ ] Describe connection to clients with oAuth and document admin settings https://github.com/owncloud/documentation/issues/3299
- [ ] Document/Update apache recommendations on how to integrate OAuth2 app in Shibboleth setups - https://github.com/owncloud/documentation/issues/3456

**Build & Marketplace release**
- [x] Bump version in info.xml (https://github.com/owncloud/oauth2/commit/acdd930c75300d8dad2c17f2534507d125828604)
- [x] Update CHANGELOG.md (https://github.com/owncloud/oauth2/commit/acdd930c75300d8dad2c17f2534507d125828604)
- [x] Create github tag for '$version'
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [x] Rename QA milestone to '$version'
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section (https://github.com/owncloud/oauth2/pull/102/commits/457d626f9b6a034ab88381068a11adca8a82ee50)
- [x] Create PR to merge changes back to `master` - #102 

cc 
@pmaier1 - any updates needed from PM?
@SergioBertolinSG , @davitol - anything needed for testplans?

**Comment by SamuAlfageme** [comment]
QA-ready as per https://github.com/owncloud/oauth2/pull/100#pullrequestreview-79171011

**Comment by pmaier1** [comment]
> QA-ready as per #100 (review)

Thanks!

No marketing or similar needed. Still waiting for docs but not a release blocker, of course.
This is good to go :+1:

**Comment by patrickjahns** [comment]
@pmaier1 
Released - close if you see fit

**Comment by SamuAlfageme** [comment]
Closing as version was released; docs still ongoing.
