### ISSUE TITLE
0.2.2 release checklist 

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/oauth2#116]
**When marking a task as done, please add your name to the task!**

### Reason
- Release needed for "ticket X", "feature Y"

### QA
- [x] Create release branch https://github.com/owncloud/oauth2/tree/release/0.2.2    @davitol
- [x] Create "$version Testplan" @davitol
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) https://github.com/owncloud/oauth2/issues/121 @davitol

### Marketing
- [x] Ping RocketChat channel #marketing @patrickjahns
- [ ] ~~Check/adapt info.xml stuff~~
- [ ] ~~Check/adapt screenshot~~
- [ ] Blog post or other communication if applicable

### Documentation
- [ ] Changes in the docs needed?

### Build & Marketplace release

- [x] Bump version in info.xml @patrickjahns
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' @patrickjahns
- [x] Create github tag for '$version' @patrickjahns
- [x] Build and sign tarball from github tag '$version' @patrickjahns
- [x] Upload to marketplace @patrickjahns
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns
- [x] Rename QA milestone to '$version' @patrickjahns
- [x] Add a new 'Unreleased' section in CHANGELOG.md @patrickjahns
- [x] Create PR to merge changes back to `master` @patrickjahns

### Specifics

- Open tickets before QA can start
- Other specifics for app release

**Comment by DeepDiver1975** [comment]
has to be part of the release: https://github.com/owncloud/oauth2/pull/118
