### ISSUE TITLE
[For 10.1] OAuth2 0.3.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/oauth2#181]
### Reason

- [x] set max version to 10 for Semver: https://github.com/owncloud/oauth2/pull/180
- [x] Add occ oauth2:remove-client to remove a client by it\s id - [#178](https://github.com/owncloud/oauth2/issues/178)
- [x] Don't fail if the client was already added - [#176](https://github.com/owncloud/oauth2/issues/176)
- [x] Add support for implicit grant - [#166](https://github.com/owncloud/oauth2/issues/166)
- [x] Add PHP 7.1 and 7.2 to stable10 tests - [#161](https://github.com/owncloud/oauth2/issues/161)
- [x] Use markdown properly in description - [#153](https://github.com/owncloud/oauth2/issues/153)
- [x] autofocus https://github.com/owncloud/oauth2/pull/173
- ~~refreshtoken lifetime added: https://github.com/owncloud/oauth2/pull/182~~ => deferred due to complications

### QA
- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa` 
- [x] Create release branch with the format "release-$version"
- [x] Create "OAuth2 0.3.0 Testplan" https://github.com/owncloud/oauth2/issues/184
- [x] Document test and set QA-ready label

### Documentation
- [ ] Changes in the docs needed?

### Marketing
- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build & Marketplace release

All actions to be done on the release branch from here:
- [x] Bump version in info.xml: https://github.com/owncloud/oauth2/pull/183
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version - $currentDate' (ex: 3.1.5 - 2018-08-01): https://github.com/owncloud/oauth2/pull/183
- [x] Create github tag for 'v${version}RC1'
- [x] Build and sign RC tarball from github tag 'v${version}RC1' with `make dist` => https://cloud.owncloud.com/index.php/s/GdXM6dVCoUp9Wos
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing
- [x] Create github tag for final 'v${version}'
- [x] Build and sign final tarball from github tag 'v${version}' with `make dist`
- [x] Smoke test tarball (at least install + enable)
- [x] Upload to marketplace
- [x] Publish for customers
- [x] Send mail to release-coordination with link to this ticket and to the changelog
- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md
- [x] Create PR to merge changes back to the `master` branch: https://github.com/owncloud/oauth2/pull/185

**Comment by PVince81** [comment]
@davitol please test RC https://cloud.owncloud.com/index.php/s/GdXM6dVCoUp9Wos

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready

**Comment by PVince81** [comment]
@DeepDiver1975 please push https://cloud.owncloud.com/index.php/s/GyLbWZIt7or5BAy to marketplace

changelog: https://github.com/owncloud/oauth2/blob/release-0.3.0/CHANGELOG.md#030
