### ISSUE TITLE
Tracking test results for OAuth2 0.3.0

### ISSUE THREAD

**Issue by davitol** [owncloud/oauth2#184]
Tested on ownCloud 10.0.10 and using OAuth2 tarball provided here: https://cloud.owncloud.com/index.php/s/GdXM6dVCoUp9Wos

### Changelog

- [x] set max version to 10 for Semver: https://github.com/owncloud/oauth2/pull/180
- [x] Add occ oauth2:remove-client to remove a client by it\s id - [#178](https://github.com/owncloud/oauth2/issues/178)**Tested running the command deleting an ID from IOS located in https://github.com/owncloud/ios/blob/cdc72af2de3bb98c7fdaaec75b568ff153104419/Owncloud%20iOs%20Client/Branding/Customization.h#L137**
- [x] Don't fail if the client was already added - [#176](https://github.com/owncloud/oauth2/issues/176)
- [x] Add support for implicit grant - [#166](https://github.com/owncloud/oauth2/issues/166) **Tested with the steps defined here: https://github.com/owncloud/oauth2/pull/166#issue-222165556**
- [x] Add PHP 7.1 and 7.2 to stable10 tests - [#161](https://github.com/owncloud/oauth2/issues/161) **CI test running in PHP 7.2**
- [x] Use markdown properly in description - [#153](https://github.com/owncloud/oauth2/issues/153)
- [x] autofocus https://github.com/owncloud/oauth2/pull/173
