### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by joneug** [owncloud/oauth2#32]
For distribution it would be nice to list this app in the ownCloud app store or to include it in the core by default.

@DeepDiver1975 Which is the preferred way?

**Comment by DeepDiver1975** [comment]
Based on the last discussions I guess we will ship this app.

**Comment by felixboehm** [comment]
It makes sense to ship it with core, to have it always on board.
Can we still provide updates via marketplace?

**Comment by DeepDiver1975** [comment]
based o the current situation I'd shipp this via the marketplace only

**Comment by felixboehm** [comment]
QA 
- [ ] create testplan, TODO Link to issue
- [ ] test and document in testplan. Final release "Go"

Build
- [ ] sign and build tarball
- [ ] upload to marketplace

Docs
- [ ] Describe connection to clients with oAuth

Communication
- Blogpost on .org ?
