### ISSUE TITLE
0.2.0 Release checklist 

### ISSUE THREAD

**Issue by felixboehm** [owncloud/oauth2#57]
QA 
- [x] create release branch: https://github.com/owncloud/oauth2/pull/84
- [x] bump version to 0.1.2
- [x] create testplan and test cases https://github.com/owncloud/oauth2/issues/63
- [x] test and document in testplan. Final release "Go"

Marketing
- [x] Update info.xml (summary, description, etc.) https://github.com/owncloud/oauth2/pull/78
- [x] Find screenshot/image https://github.com/owncloud/oauth2/pull/78
- [x] Add changelog https://github.com/owncloud/oauth2/issues/82

Build
- [x] update translations
- [x] sign and build tarball
- [x] upload to marketplace

Docs
- [ ] Describe connection to clients with oAuth and document admin settings https://github.com/owncloud/documentation/issues/3299
- [ ] Document/Update apache recommendations on how to integrate OAuth2 app in Shibboleth setups - https://github.com/owncloud/documentation/issues/3456

Communication
- [x] Blogpost on .org ?

**Comment by SamuAlfageme** [comment]
There's some work already going by @jesmrec on on the testplan design for mobile apps: https://github.com/owncloud/QA/pull/468 - this is most likely applicable to every single app using OAuth as authentication method. 

A more generic version might need to be platform-agnostic (i.e. no mobile usual actions, such orientation)

**Comment by pmaier1** [comment]
added Marketing tasks

**Comment by michaelstingl** [comment]
OAuth2 looks great in the Marketplace. Thank you guys!

**Comment by patrickjahns** [comment]
@pmaier1 
can this be closed? app is published

**Comment by pmaier1** [comment]
Basically we were waiting for the two (still) open doc tickets as this was the initial release. As were now doing another release we can close this, yes.
