### ISSUE TITLE
0.2.0 Testplan 

### ISSUE THREAD

**Issue by felixboehm** [owncloud/oauth2#63]
Needs:
- ✅ [CORS] **Requests against some /ocs endpoints return empty body and invalidate the session if OAuth2 is enabled.** https://github.com/owncloud/core/issues/28860
- ✅ [LDAP] - Accounts from the LDAP user backend get replied with the UUID as user_id on the authorize call -> #74
- 🔓 Introduce UserSession::verifyAuthHeaders which validates the session -> https://github.com/owncloud/core/pull/28733

Please add test cases and test results here.
@jesmrec @davitol @SamuAlfageme @michaelstingl 

# App-centric testplan:

- [x] Server (app) testplan: https://github.com/owncloud/QA/issues/485 @SamuAlfageme

# Sync Client

- [x] Desktop's support test plan: https://github.com/owncloud/QA/pull/473 @SamuAlfageme

# iOS 

Updated on 31/08/2017

- [ ] Test plan: https://github.com/owncloud/QA/pull/474 [WIP]
- [X] Bugs found during QA in progress are tracked in https://github.com/owncloud/ios/pull/919 ; summary is:
- [X] Dev-in-progress: refresh of access token, tracked in https://github.com/owncloud/ios/issues/928 . We moved it so that testing on the rest of the feature can start sooner, but the iOS app should not be released with OAuth support enabled until this issue is developed and tested too.
- [ ] QA including refresh token [WIP]

# Android

Updated on 31/08/2017

**QA Approved**

- [X] Test plan: https://github.com/owncloud/QA/pull/474 
- [X] Bugs found during QA in progress are tracked in https://github.com/owncloud/android/issues/1724 ; summary is:
- - 10 bugs found & solved
- - QA finished.
- - Merged and ready to be published in 2.5.0

**Comment by SamuAlfageme** [comment]
## Current Status:

- [ ] 🔓 Setting the user on the login form when sent as `user` in the auth. request https://github.com/owncloud/oauth2/pull/67
- [ ]  🔐 Switching the user when trying to login with a different one (see https://github.com/owncloud/oauth2/issues/48#issuecomment-315347435)
- [ ]  🔐 Race condition in https://github.com/owncloud/oauth2/pull/65#issuecomment-318595228 

## Input required:

- [ ] Discussion on migration paths in the clients on: https://github.com/owncloud/client/issues/5848#issuecomment-318324915:

>  What to do when upgrading a client with an account which has a valid session on a server that does support OAuth2 **or** enabling the OAuth2 application on the server while the clients have valid sessions?

> (Since the server stills supports basic auth. and the client does have a password/session stored, it will login normally)

cc/ @DeepDiver1975 

## Testplan compliance:

🔐 - Will start running https://github.com/owncloud/QA/pull/473's testplan as soon as the blockers described above are merged.

cc/ @felixboehm

**Comment by davivel** [comment]
> Discussion on migration paths in the clients

@michaelstingl , @felixboehm , this seems important. We didn't consider this in the clients good enough.

When we release the clients with OAuth2 support, we should expect that many **current** OC users are interested in it, and they will expect that the change is seamless. They will expect that their current accounts using basic auth can be **upgraded to OAuth2 without having to delete, create and sync them again** . 

And with the scope we had in mind for the release of OAuth2 this is just not true.

This is not trivial, and would delay, once again, the release of OAuth2 support in clients, but it's not something we can ignore.

Any other opinions about it?

**Comment by nasli** [comment]
On the iOS side we can take advantage of the migration of URL feature. 
But in any case will increase also the logic and scope of the current approach.

**Comment by michaelstingl** [comment]
I think people will enable OAuth for testing and expect it just works. Some might disable it on the server because they don't like, and probably expect login still works.

If we release OAuth support as a tech preview in the next mobile releases, we would need at least a warning message that tells the user what is going on and how to resolve it. (reinstall app, remove account…). Perhaps then it would be enough to ship migration in the next release. Behaviour should be similar in desktop, Android, iOS in the end.

**Comment by davivel** [comment]
@pmaier1 , I update the first comment with the current state of support in mobile apps.

**Comment by pmaier1** [comment]
> @pmaier1 , I update the first comment with the current state of support in mobile apps. Do you need more details?

Thanks! This is enough, I think.

**Comment by davivel** [comment]
Updated state of mobile apps in first comment.

**Comment by SamuAlfageme** [comment]
I'm also opening & auto-assigning an issue for an app-centric tesplan for the OAuth app: https://github.com/owncloud/QA/issues/485 

This one will include actions like handling client id/secrets, removing OAuth sessions, etc.

**Comment by patrickjahns** [comment]
Is there anything to be done here - or closing?

**Comment by SamuAlfageme** [comment]
@patrickjahns updated the "blockers" status on https://github.com/owncloud/oauth2/issues/63#issue-243462031 with the latest developments in https://github.com/owncloud/core/pull/28733 (need to test this tho) -> it will close https://github.com/owncloud/oauth2/issues/89 

Apart from that, there's some more things to consider in order to improve the production-readiness of this version of the OAuth2 app; these are some: 

- [ ] Unchecked boxes on https://github.com/owncloud/oauth2/issues/63#issuecomment-319038407
    - [ ] Race condition on https://github.com/owncloud/oauth2/issues/70 (edge case; requires 2 accounts signed in the same client requesting an access token closely in time; no big blocker)
    - [ ] Client migrations: https://github.com/owncloud/client/issues/5848#issuecomment-318324915 and https://github.com/owncloud/client/issues/6198 (to be read in context together with https://github.com/owncloud/core/issues/29300)
- [ ] Documentation:
    - [ ] General docs. on the app: https://github.com/owncloud/documentation/issues/3299 
    - [ ] Better describe the Apache configuration required by the app: https://github.com/owncloud/oauth2/issues/49 (we need to understand why e.g. some legacy configs not updated together with apache filter out the Auth. headers...)
    - [ ] Shibboleth wrapping: https://github.com/owncloud/documentation/issues/3456

**Comment by patrickjahns** [comment]
The question was related, if there are things to be done related this ticket topic "testplan 0.2.0" - not what needs to be done with the app itself. 

If the testplan for 0.2.0 was completed, we should close the issue - or otherwise document what needs to be done for having a proper testplan for this app

**Comment by SamuAlfageme** [comment]
> otherwise document what needs to be done for having a proper testplan for this app

- App: https://github.com/owncloud/QA/pull/498
- Desktop Client integration: https://github.com/owncloud/QA/pull/473
- Mobile clients integration: https://github.com/owncloud/QA/pull/474

Due to the special nature of the app, these 3 testplans complement each other. I think for the current state (as in version 0.2 - still a _tech preview_: https://github.com/owncloud/oauth2/issues/63#issuecomment-319635920) of this app is enough. 

Closing here. Will try to come up with a way to better express my production-readiness ideas for the app.
